spring.application.name=personal-trainer

spring.datasource.url=jdbc:postgresql://localhost:5432/personal_trainer_db
spring.datasource.username=postgres
spring.datasource.password=personaltrainer

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT - em prod
jwt.secret=chave-secreta-para-avaliacao-do-professor-2026-ufape-personal-trainer
jwt.expiration=3600000

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO

spring.jpa.open-in-view=true